services:
  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./assets/elastic/data/:/usr/share/elasticsearch/data
    mem_limit: "1g"

  fluentd:
    image: fluent/fluent-bit
    volumes: 
      - ./assets/fluent:/fluent-bit/etc/
    ports: 
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.13.0
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  jarl:
    container_name: jarl
    build: .
    ports:
      - 8000:8000
      - 9000:9000
    environment:
      - AUTHZ_HEADER=x-forwarded-sub
    logging:
      driver: fluentd
      options:
        tag: jarl
        fluentd-async: 'true'
    restart: always
    depends_on:
      - fluentd